# importing all the tampering scripts (credits to WhatWaf )
from tampers.apostrephemask import *
from tampers.apostrephenullify import *
from tampers.appendnull import *
from tampers.base64encode import *
from tampers.booleanmask import *
from tampers.doubleurlencode import *
from tampers.enclosebrackets import *
from tampers.escapequotes import *
from tampers.lowercase import *
from tampers.maskenclosebrackets import *
from tampers.modsec import *
from tampers.modsecspace2comment import *
from tampers.obfuscatebyhtmlentity import *
from tampers.obfuscatebyordinal import *
from tampers.prependnull import *
from tampers.randomcase import *
from tampers.randomcomments import *
from tampers.randomjunkcharacters import *
from tampers.randomtabify import *
from tampers.randomunicode import *
from tampers.randomwildcard import *
from tampers.space2comment import *
from tampers.space2doubledash import *
from tampers.space2hash import *
from tampers.space2multicomment import *
from tampers.space2null import *
from tampers.space2plus import *
from tampers.space2randomblank import *
from tampers.tabifyspacecommon import *
from tampers.tabifyspaceuncommon import *
from tampers.tripleurlencode import *
from tampers.uppercase import *
from tampers.urlencodeall import *
from tampers.urlencode import *
